#!/usr/bin/env ruby
# coding: utf-8

require_relative 'lib/ipv4'
require_relative 'lib/device'
require_relative 'lib/router'

require 'optparse'
$opt = OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} -r IP/CIDR [,IP/CIDR]+ \n\n" \
  "Example: #{$0} -r 1.1.1.1/26,1.1.1.2/24"

  opts.on("-r=ip1,ip2,..", Array, "Example: -r 1.1.1.1/26,1.1.1.2/24") do |a|
    $reachables = true
    $ip1 = IPv4.new a[0]
    $ips = a[1..-1].map{|ip| IPv4.new ip}
  end

  opts.on("-i", "--interactive") do
    $interactive = true
  end

  if ARGV.empty?
    puts opts.banner
  end

end.parse!

def interactive
  network = []
  loop do
    require 'pry'
    binding.pry
  end
end

def reachables
  puts "-"*6 + "|" + "-"*67,
       "base  | " + $ip1.to_s,
       "-"*6 + "|" + "-"*67
  $ips.each do |ip|
    err = [$ip1.can_reach?(ip), ip.can_reach?($ip1)]
    r = "yes  "
    if err.include? false
      err_disp = ""
      err_disp += err[0] ? "." : "!"
      err_disp += err[1] ? "." : "!"
      r = "err#{err_disp}"
    end
    puts "#{r} | #{ip}"
  end
end

if __FILE__ == $0
  interactive if $interactive
  reachables if $reachables
end
